# Workflow responsible for building and publishing repository artifacts.
name: Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

env: 
  GH_TOKEN:  ${{ secrets.EMR_DEVOPS_CONTAINERS_TOKEN }}
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest version of code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          
      - name: move .releaserc file
        run: mv .github/.releaserc .
  
      - name: Setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      
      - name: Dry run to get the next release version
        id: tag_version
        run: |
          echo "TAG=$( npx semantic-release --dry-run | grep -oP 'The next release version is \K\S+' | awk '{print $1}' )" >> $GITHUB_ENV

      - name: Run semantic-release
        run: |
          npx semantic-release
    
      - name: Log in to the Container registry
        if: ${{ env.TAG != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ env.TAG != '' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: |
             ghcr.io/vauotto/emr-node-build-container
             ghcr.io/vauotto/emr-node-dev-container
      
      - name: Set up QEMU
        if: ${{ env.TAG != '' }}
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        if: ${{ env.TAG != '' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and publish Images
        if: ${{ env.TAG != '' }}
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl
          workdir: container/node
          push: true