# Workflow responsible for building and publishing repository artifacts.
name: Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

env: 
  GH_TOKEN:  ${{ secrets.EMR_DEVOPS_CONTAINERS_TOKEN }}
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]

    steps:
      - name: Get latest version of code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      
      - name: Run semantic-release
        run: |
          npx semantic-release
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: |
             ghcr.io/philips-internal/emr-node-build-container
             ghcr.io/philips-internal/emr-node-dev-containe

      - name: Build and publish Images
        uses: docker/bake-action@v4
        with:
          files: ./container/node/docker-bake.hcl
          push: true
